---
- name: Delete Azure VM
  hosts: localhost
  connection: local
  collections:
    - azure.azcollection
  tasks:
    - name: Delete VM script extension to enable HTTPS WinRM listener
      azure_rm_virtualmachineextension:
        name: lab001winrmextension
        resource_group: lab001rg
        virtual_machine_name: lab001vm
        state: absent
      register: out_extension
    - debug:
        var: out_extension

    - name: Delete VM
      azure_rm_virtualmachine:
        resource_group: lab001rg
        name: lab001vm
        state: absent
      register: out_vm
    - debug:
        var: out_vm

    - name: Delete a network interface
      azure_rm_networkinterface:
        name: lab001nic
        resource_group: lab001rg
        virtual_network: lab001vnet
        subnet_name: lab001subnet
        security_group: lab001nsg
        state: absent
      register: out_nic
    - debug:
        var: out_nic

    - name: Delete Network Security Group
      azure_rm_securitygroup:
        resource_group: lab001rg
        name: lab001nsg
        state: absent
      register: out_nsg
    - debug:
        var: out_nsg

    - name: Delete public IP address
      azure_rm_publicipaddress:
        resource_group: lab001rg
        name: lab001publicip
        state: absent
      register: out_publicip
    - debug:
        var: out_publicip

    - name: Delete subnet
      azure_rm_subnet:
        resource_group: lab001rg
        virtual_network: lab001vnet
        name: lab001subnet
        state: absent
      register: out_subnet
    - debug:
        var: out_subnet

    - name: Delete virtual network
      azure_rm_virtualnetwork:
        resource_group: lab001rg
        name: lab001vnet
        state: absent
      register: out_vnet
    - debug:
        var: out_vnet

    - name: Delete resource group
      azure_rm_resourcegroup:
        name: lab001rg
        state: absent
      register: out_rg
    - debug:
        var: out_rg
