- hosts: localhost
  connection: local
  collections:
    - azure.azcollection
  tasks:
    - name: Deleting resource group
      azure_rm_resourcegroup:
        name: "ansible-test1"
        state: absent
      register: rg
    - debug:
        var: rg
