---
- name: Create Azure VM
  hosts: localhost
  connection: local
  collections:
    - azure.azcollection
  vars_prompt:
    - name: windowsadmin_password
      prompt: "Enter Windows local Administrator password"
    - name: linuxroot_password
      prompt: "Enter Linux root password"
    - name: ssh_publickey
      prompt: "Enter SSH public key"
    - name: home_ip_range
      prompt: "Enter your home IP range e.g. 1.2.3.4/32"
  tasks:
    - name: Create resource group
      azure_rm_resourcegroup:
        name: lab001rg
        location: australiaeast

    - name: Create virtual network
      azure_rm_virtualnetwork:
        resource_group: lab001rg
        name: lab001vnet
        address_prefixes: "10.0.0.0/16"

    - name: Add subnet
      azure_rm_subnet:
        resource_group: lab001rg
        name: lab001subnet
        address_prefix: "10.0.1.0/24"
        virtual_network: lab001vnet

    - name: Create public IP address
      azure_rm_publicipaddress:
        resource_group: lab001rg
        allocation_method: Static
        name: lab001publicip1
      register: output_ip_address1

    - name: Output public IP
      debug:
        msg: "The Windows Server public IP is {{ output_ip_address1.state.ip_address }}"

    - name: Create Network Security Group
      azure_rm_securitygroup:
        resource_group: lab001rg
        name: lab001nsg1
        rules:
          - name: "allow_rdp"
            protocol: Tcp
            destination_port_range: 3389
            access: Allow
            priority: 1001
            direction: Inbound
            source_address_prefix: "{{ home_ip_range }}"
          - name: "allow_web_traffic"
            protocol: Tcp
            destination_port_range:
              - 80
              - 443
            access: Allow
            priority: 1002
            direction: Inbound
            source_address_prefix: "{{ home_ip_range }}"
          - name: "allow_powershell_remoting"
            protocol: Tcp
            destination_port_range:
              - 5985
              - 5986
            access: Allow
            priority: 1003
            direction: Inbound
            source_address_prefix: "{{ home_ip_range }}"

    - name: Create a network interface
      azure_rm_networkinterface:
        name: lab001nic1
        resource_group: lab001rg
        virtual_network: lab001vnet
        subnet_name: lab001subnet
        security_group: lab001nsg1
        ip_configurations:
          - name: default
            public_ip_address_name: lab001publicip1
            primary: True
            private_ip_allocation_method: Static
            private_ip_address: "10.0.1.4"

    - name: Create VM
      azure_rm_virtualmachine:
        resource_group: lab001rg
        name: lab001vm1
        vm_size: Standard_DS3_v2 # Standard_DS1_v2, too small
        admin_username: azureuser
        admin_password: "{{ windowsadmin_password }}"
        network_interface_names: lab001nic1
        os_type: Windows
        managed_disk_type: Premium_LRS # StandardSSD_LRS, Standard_LRS
        image:
          offer: WindowsServer
          publisher: MicrosoftWindowsServer
          sku: 2022-Datacenter
          version: latest
        winrm:
          - protocol: http # https

    - name: Create VM script extension to enable HTTPS WinRM listener
      azure_rm_virtualmachineextension:
        name: lab001winrmextension
        resource_group: lab001rg
        virtual_machine_name: lab001vm1
        publisher: Microsoft.Compute
        virtual_machine_extension_type: CustomScriptExtension
        type_handler_version: "1.9"
        settings: '{"fileUris": ["https://raw.githubusercontent.com/ansible/ansible/devel/examples/scripts/ConfigureRemotingForAnsible.ps1"],"commandToExecute": "powershell -ExecutionPolicy Unrestricted -File ConfigureRemotingForAnsible.ps1"}'
        auto_upgrade_minor_version: true

    # - name: wait for the WinRM port to come online
    #   wait_for:
    #     port: 5986
    #     host: "{{ output_ip_address1 }}"
    #     timeout: 600

    # ---- machine 2

    - name: Create public IP address
      azure_rm_publicipaddress:
        resource_group: lab001rg
        allocation_method: Static
        name: lab001publicip2
      register: output_ip_address2

    - name: Output public IP of machine 2
      debug:
        msg: "The Linux server public IP is {{ output_ip_address2.state.ip_address }}"

    - name: Create Network Security Group
      azure_rm_securitygroup:
        resource_group: lab001rg
        name: lab001nsg2
        rules:
          - name: "allow_ssh"
            protocol: Tcp
            destination_port_range: 22
            access: Allow
            priority: 1001
            direction: Inbound
            source_address_prefix: "{{ home_ip_range }}"
          - name: "allow_web_traffic"
            protocol: Tcp
            destination_port_range:
              - 80
              - 443
            access: Allow
            priority: 1002
            direction: Inbound
            source_address_prefix: "{{ home_ip_range }}"
          - name: "allow_cockpit"
            protocol: Tcp
            destination_port_range:
              - 9090
            access: Allow
            priority: 1003
            direction: Inbound
            source_address_prefix: "{{ home_ip_range }}"

    - name: Create a network interface
      azure_rm_networkinterface:
        name: lab001nic2
        resource_group: lab001rg
        virtual_network: lab001vnet
        subnet_name: lab001subnet
        security_group: lab001nsg2
        ip_configurations:
          - name: default
            public_ip_address_name: lab001publicip2
            primary: True
            private_ip_allocation_method: Static
            private_ip_address: "10.0.1.5"

    - name: Create VM
      azure_rm_virtualmachine:
        resource_group: lab001rg
        name: lab001vm2
        vm_size: Standard_DS3_v2 # Standard_DS1_v2, too small
        network_interface_names: lab001nic2
        managed_disk_type: Premium_LRS # StandardSSD_LRS, Standard_LRS
        image:
          offer: rockylinux-9
          publisher: erockyenterprisesoftwarefoundationinc1653071250513
          sku: rockylinux-9
          version: latest
        plan:
          name: rockylinux-9
          product: rockylinux-9
          publisher: erockyenterprisesoftwarefoundationinc1653071250513
        admin_username: azureuser
        admin_password: "{{ linuxroot_password }}"
        ssh_password_enabled: true
        ssh_public_keys:
          - path: /home/azureuser/.ssh/authorized_keys
            key_data: "{{ ssh_publickey }}"

    - name: wait for the SSH port to come online
      wait_for:
        host: "{{ output_ip_address2 }}"
        port: 22
        timeout: 600
        connect_timeout: 300
        delay: 10
