---
- name: Creating Azure VM
  hosts: localhost
  connection: local
  collections:
    - azure.azcollection
  vars_prompt:
    - name: windowsadmin_password
      prompt: "Enter Windows local Administrator password"
    - name: home_ip_range
      prompt: "Enter your home IP range e.g. 1.2.3.4/32"
      private: false

  tasks:
    - name: Creating resource group
      azure_rm_resourcegroup:
        name: lab001rg
        location: australiaeast

    - name: Creating virtual network
      azure_rm_virtualnetwork:
        resource_group: lab001rg
        name: lab001vnet
        address_prefixes: "10.0.0.0/16"

    - name: Adding subnet
      azure_rm_subnet:
        resource_group: lab001rg
        name: lab001subnet
        address_prefix: "10.0.1.0/24"
        virtual_network: lab001vnet

    - name: Creating public IP address 1 - Windows
      azure_rm_publicipaddress:
        resource_group: lab001rg
        allocation_method: Static
        name: lab001publicip1
      register: output_ip_address1

    - name: Showing public IP 1 - Windows
      debug:
        msg: "The Windows Server public IP is {{ output_ip_address1.state.ip_address }}"

    - name: Creating Network Security Group 1 - Windows
      azure_rm_securitygroup:
        resource_group: lab001rg
        name: lab001nsg1
        rules:
          - name: "allow_rdp"
            protocol: Tcp
            destination_port_range: 3389
            access: Allow
            priority: 1001
            direction: Inbound
            source_address_prefix: "{{ home_ip_range }}"
          - name: "allow_web_traffic"
            protocol: Tcp
            destination_port_range:
              - 80
              - 443
            access: Allow
            priority: 1002
            direction: Inbound
            source_address_prefix: "{{ home_ip_range }}"
          - name: "allow_powershell_remoting"
            protocol: Tcp
            destination_port_range:
              - 5985
              - 5986
            access: Allow
            priority: 1003
            direction: Inbound
            source_address_prefix: "{{ home_ip_range }}"
          - name: "allow_windows_admin_center"
            protocol: Tcp
            destination_port_range:
              - 6516
            access: Allow
            priority: 1004
            direction: Inbound
            source_address_prefix: "{{ home_ip_range }}"

    - name: Creating a network interface 1 - Windows
      azure_rm_networkinterface:
        name: lab001nic1
        resource_group: lab001rg
        virtual_network: lab001vnet
        subnet_name: lab001subnet
        security_group: lab001nsg1
        ip_configurations:
          - name: default
            public_ip_address_name: lab001publicip1
            primary: True
            private_ip_allocation_method: Static
            private_ip_address: "10.0.1.4"

    - name: Creating VM 1 - Windows
      azure_rm_virtualmachine:
        resource_group: lab001rg
        name: lab001vm1
        vm_size: Standard_DS3_v2 # Standard_DS1_v2, too small
        admin_username: azureuser
        admin_password: "{{ windowsadmin_password }}"
        network_interface_names: lab001nic1
        os_type: Windows
        managed_disk_type: Premium_LRS # StandardSSD_LRS, Standard_LRS
        image:
          offer: WindowsServer
          publisher: MicrosoftWindowsServer
          sku: 2022-Datacenter
          version: latest
        winrm:
          - protocol: http # https

    - name: Creating VM script extension to enable HTTPS WinRM listener
      azure_rm_virtualmachineextension:
        name: lab001winrmextension
        resource_group: lab001rg
        virtual_machine_name: lab001vm1
        publisher: Microsoft.Compute
        virtual_machine_extension_type: CustomScriptExtension
        type_handler_version: "1.9"
        settings: '{"fileUris": ["https://raw.githubusercontent.com/ansible/ansible/devel/examples/scripts/ConfigureRemotingForAnsible.ps1"],"commandToExecute": "powershell -ExecutionPolicy Unrestricted -File ConfigureRemotingForAnsible.ps1"}'
        auto_upgrade_minor_version: true

    # ---- Are we up

    - name: Getting facts for one Public IP 1 - Windows
      azure_rm_publicipaddress_info:
        resource_group: lab001rg
        name: lab001publicip1
      register: publicipaddresses1

    - name: Setting public IP address fact 1 - Windows
      set_fact: publicipaddress1="{{ publicipaddresses1 | json_query('publicipaddresses[0].ip_address')}}"

    - name: Waiting for the WinRM port to come online - Windows
      wait_for:
        port: 5986
        host: "{{ publicipaddress1 }}"
        timeout: 600
