---
- name: Windows Server - Install RSAT and Windows Updates
  hosts: dc
  collections:
    - ansible.windows.win_feature
    - ansible.windows.win_updates
    - ansible.windows.win_reboot
  vars_prompt:
    - name: ansible_password
      prompt: "Enter local / built-in Administrator password"
  tasks:
    - name: Installing RSAT
      ansible.windows.win_feature:
        include_sub_features: yes
        name: RSAT
    - name: Rebooting after RSAT
      ansible.windows.win_reboot:
    - name: Installing all updates and rebooting again if needed
      ansible.windows.win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
          - UpdateRollups
        state: installed
        reboot: true
