---
- name: Installing extra software on Windows server
  hosts: dc
  collections:
    - chocolatey.chocolatey.win_chocolatey
    - ansible.windows.win_updates
    - ansible.windows.win_reboot

  vars_prompt:
    - name: ansible_password
      prompt: "Enter local / built-in Administrator password"

  tasks:
    - name: Installing Windows Admin Center
      win_chocolatey:
        name: windows-admin-center
        state: present

    - name: Rebooting after Windows Admin Center
      ansible.windows.win_reboot:

    - name: Installing PowerShell Core
      win_chocolatey:
        name: powershell-core
        state: present

    - name: Installing Microsoft Sysinternals
      win_chocolatey:
        name: sysinternals

    # - name: Installing Microsot Visual Studio Code
    #   win_chocolatey:
    #     name: vscode.install
    #     state: present

    # - name: Installing Git
    #   win_chocolatey:
    #     name: git.install
    #     state: present

    # - name: Installing Python 3
    #   win_chocolatey:
    #     name: python3
    #     state: present

    - name: Rebooting after all installs
      ansible.windows.win_reboot:
