---
- name: Post DC
  hosts: dc
  collections:
    - ansible.windows.win_updatees
    - ansible.windows.win_domain_controller
  vars_prompt:
    - name: ansible_password
      prompt: "Enter local / built-in Administrator password"
    - name: adsafemode_password
      prompt: "Enter AD safe mode password"
  tasks:
    - name: Install all updates and reboot as many times as needed
      ansible.windows.win_updates:
        category_names: "*"
        reboot: yes
    - name: Promote to Domain Controller
      win_domain:
        safe_mode_password: { adsafemode_password }
        install_dns: yes
        dns_domain_name: paradoxus.local
      register: active_directory_controllers
    - name: Reboot Domain Controller after promotion
      win_reboot:
      when: active_directory_controllers.reboot_required
