---
- name: Post DC
  hosts: dc
  collections:
    - ansible.windows.win_updates
    - ansible.windows.win_domain_controller
    - ansible.windows.win_reboot
  vars_prompt:
    - name: ansible_password
      prompt: "Enter local / built-in Administrator password"
    - name: adsafemode_password
      prompt: "Enter AD safe mode password"
    - name: ad_dns_domain_name
      prompt: "Enter AD DNS domain name e.g. domain.local"
      private: false
  tasks:
    - name: Install all updates and reboot as many times as needed
      ansible.windows.win_updates:
        state: installed
        reboot: true
    - name: Promote to Domain Controller
      ansible.windows.win_domain:
        safe_mode_password: { adsafemode_password } }
        install_dns: yes
        dns_domain_name: { { ad_dns_domain_name } }
      register: active_directory_controllers
    - name: Reboot Domain Controller after promotion
      ansible.windows.win_reboot:
      when: active_directory_controllers.reboot_required
