---
- name: Upgrade Windows server to Domain Controller
  hosts: dc
  collections:
    - ansible.windows.win_domain
  vars_prompt:
    - name: ansible_password
      prompt: "Enter local / built-in Administrator password"
    - name: adsafemode_password
      prompt: "Enter AD safe mode password"
    # - name: ad_dns_domain_name
    #   prompt: "Enter AD DNS domain name e.g. domain.local"
    #   private: false
  tasks:
    - name: Creating new domain, promoting server to domain controller
      ansible.windows.win_domain:
        safe_mode_password: "{{ adsafemode_password }}"
        install_dns: yes
        dns_domain_name: "{{ ad_dns_domain_name }}"
      register: domaincreate
    - name: Rebooting domain controller after new domain + promotion
      ansible.windows.win_reboot:
      when: domaincreate.reboot_required
