- name: Creating OUs
  hosts: dc
  collections:
    - community.windows.win_domain_ou
  vars_prompt:
    - name: ansible_user
      prompt: "Enter DOMAIN Administrator user UPN (user@dns.domain)"
      private: false
    - name: ansible_password    
      prompt: "Enter DOMAIN Administrator password"
    # - name: ad_domain_dn
    #   prompt: "Enter AD DNS domain name e.g. DC=domain,DC=local"
    #   private: false
  tasks:
    - name: Creating 'Computer Accounts' OU
      community.windows.win_domain_ou:
        name: Computer Accounts
        path: "{{ ad_domain_dn }}"
        state: present
        protected: false
    - name: Creating 'User Accounts' OU
      community.windows.win_domain_ou:
        name: User Accounts
        path: "{{ ad_domain_dn }}"
        state: present
        protected: false
    - name: Creating 'Our People' OU
      community.windows.win_domain_ou:
        name: Our People
        path: "OU=User Accounts,{{ ad_domain_dn }}"
        state: present
        protected: false
    - name: Creating 'Our Clients' OU
      community.windows.win_domain_ou:
        name: Our Clients
        path: "OU=User Accounts,{{ ad_domain_dn }}"
        state: present
        protected: false
    - name: Creating 'IT Consultant Non-Privileged Accounts' OU
      community.windows.win_domain_ou:
        name: IT Consultant Non-Privileged Accounts
        path: "OU=User Accounts,{{ ad_domain_dn }}"
        state: present
        protected: false
    - name: Creating 'Our People ish Test Accounts' OU
      community.windows.win_domain_ou:
        name: Our People ish Test Accounts
        path: "OU=User Accounts,{{ ad_domain_dn }}"
        state: present
        protected: false
    - name: Creating 'Our People ish Training Accounts' OU
      community.windows.win_domain_ou:
        name: Our People ish Training Accounts
        path: "OU=User Accounts,{{ ad_domain_dn }}"
        state: present
        protected: false
    - name: Creating 'Privileged Admin Accounts IT Consultants' OU
      community.windows.win_domain_ou:
        name: Privileged Admin Accounts IT Consultants
        path: "OU=User Accounts,{{ ad_domain_dn }}"
        state: present
        protected: false
    - name: Creating 'Privileged Admin Accounts Our People' OU
      community.windows.win_domain_ou:
        name: Privileged Admin Accounts Our People
        path: "OU=User Accounts,{{ ad_domain_dn }}"
        state: present
        protected: false
    - name: Creating 'Service Accounts' OU
      community.windows.win_domain_ou:
        name: Service Accounts
        path: "OU=User Accounts,{{ ad_domain_dn }}"
        state: present
        protected: false
    - name: Creating 'Service Accounts gMSA' OU
      community.windows.win_domain_ou:
        name: Service Accounts gMSA
        path: "OU=User Accounts,{{ ad_domain_dn }}"
        state: present
        protected: false
    - name: Creating 'Groups' OU
      community.windows.win_domain_ou:
        name: Groups
        path: DC=paradoxus,DC=local
        state: present
        protected: false
    - name: Creating 'IT Admin Teams' OU
      community.windows.win_domain_ou:
        name: IT Admin Teams
        path: "OU=Groups,{{ ad_domain_dn }}"
        state: present
        protected: false
    - name: Creating 'IT Admin System Roles' OU
      community.windows.win_domain_ou:
        name: IT Admin System Roles
        path: "OU=Groups,{{ ad_domain_dn }}"
        state: present
        protected: false
    - name: Creating 'Computer Accounts' OU
      community.windows.win_domain_ou:
        name: Computer Accounts
        path: DC=paradoxus,DC=local
        state: present
        protected: false
    - name: Creating 'Servers' OU
      community.windows.win_domain_ou:
        name: Servers
        path: "OU=Computer Accounts,{{ ad_domain_dn }}"
        state: present
        protected: false
    - name: Creating 'Servers Linux' OU
      community.windows.win_domain_ou:
        name: Servers Linux
        path: "OU=Computer Accounts,{{ ad_domain_dn }}"
        state: present
        protected: false
    - name: Creating 'Workstations' OU
      community.windows.win_domain_ou:
        name: End User Workstations
        path: "OU=Computer Accounts,{{ ad_domain_dn }}"
        state: present
        protected: false
    - name: Creating 'SOE Full' OU
      community.windows.win_domain_ou:
        name: SOE Full
        path: "OU=End User Workstations,OU=Computer Accounts,{{ ad_domain_dn }}"
        state: present
        protected: false
    - name: Creating 'SOE Light' OU
      community.windows.win_domain_ou:
        name: SOE Light
        path: "OU=End User Workstations,OU=Computer Accounts,{{ ad_domain_dn }}"
        state: present
        protected: false
    - name: Creating 'Windows IOT' OU
      community.windows.win_domain_ou:
        name: Windows IOT
        path: "OU=Computer Accounts,{{ ad_domain_dn }}"
        state: present
        protected: false
    - name: Creating 'Windows display panels' OU
      community.windows.win_domain_ou:
        name: Windows display panels
        path: "OU=Windows IOT,OU=Computer Accounts,{{ ad_domain_dn }}"
        state: present
        protected: false
    - name: Creating 'Teams rooms' OU
      community.windows.win_domain_ou:
        name: Teams rooms
        path: "OU=Windows IOT,OU=Computer Accounts,{{ ad_domain_dn }}"
        state: present
        protected: false
    - name: Creating 'Macintosh workstations' OU
      community.windows.win_domain_ou:
        name: Macintosh workstations
        path: "OU=End User Workstations,OU=Computer Accounts,{{ ad_domain_dn }}"
        state: present
        protected: false
    - name: Creating 'PAW' OU
      community.windows.win_domain_ou:
        name: Privileged Admin Wokrstations
        path: "OU=Computer Accounts,{{ ad_domain_dn }}"
        state: present
        protected: false
    - name: Creating 'Jump Boxes' OU
      community.windows.win_domain_ou:
        name: Privileged Admin Jump Boxes
        path: "OU=Computer Accounts,{{ ad_domain_dn }}"
        state: present
        protected: false
    - name: Creating 'End User Terminal Servers' OU
      community.windows.win_domain_ou:
        name: End User Terminal Servers
        path: "OU=Computer Accounts,{{ ad_domain_dn }}"
        state: present
        protected: false
