---
- name: Delete Azure RG
  hosts: localhost
  connection: local
  collections:
    - azure.azcollection
  tasks:
    - name: Delete resource group
      azure_rm_resourcegroup:
        name: lab001rg
        state: absent
      register: out_rg
    - debug:
        var: out_rg
/